/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.project1;

import javax.swing.DefaultListModel;

/**
 *
 * @author apple
 */
public class project1 extends javax.swing.JFrame {
    
    DefaultListModel pilih;
    /**
     * Creates new form project1
     */
    public project1() {
        initComponents();
        pilih = new DefaultListModel();
        listPilih.setModel(pilih);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chckcapuccino = new javax.swing.JCheckBox();
        chckexpressoo = new javax.swing.JCheckBox();
        chckamericano = new javax.swing.JCheckBox();
        txtcapuccino = new javax.swing.JTextField();
        txtexpresso = new javax.swing.JTextField();
        txtamericano = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radioyes = new javax.swing.JRadioButton();
        radiochange = new javax.swing.JRadioButton();
        Modern = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPilih = new javax.swing.JList<>();
        btnCopy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listToping = new javax.swing.JList<>();
        combopayment = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResume = new javax.swing.JTextArea();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        chckcapuccino.setText("Capuccino                 Rp. 3.000");
        chckcapuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckcapuccinoActionPerformed(evt);
            }
        });
        getContentPane().add(chckcapuccino);
        chckcapuccino.setBounds(20, 170, 230, 23);

        chckexpressoo.setText("Expressoo                  Rp. 8.000");
        chckexpressoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckexpressooActionPerformed(evt);
            }
        });
        getContentPane().add(chckexpressoo);
        chckexpressoo.setBounds(20, 130, 230, 23);

        chckamericano.setText("Americano                 Rp. 5.000");
        chckamericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckamericanoActionPerformed(evt);
            }
        });
        getContentPane().add(chckamericano);
        chckamericano.setBounds(20, 150, 227, 23);
        getContentPane().add(txtcapuccino);
        txtcapuccino.setBounds(310, 170, 70, 26);

        txtexpresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexpressoActionPerformed(evt);
            }
        });
        getContentPane().add(txtexpresso);
        txtexpresso.setBounds(310, 130, 70, 26);
        getContentPane().add(txtamericano);
        txtamericano.setBounds(310, 150, 70, 26);

        jPanel1.setOpaque(false);

        radioyes.setText("Yes");
        radioyes.setActionCommand("Uang Cash");
        radioyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioyesActionPerformed(evt);
            }
        });

        radiochange.setText("Change");
        radiochange.setActionCommand("Uang Cash");
        radiochange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiochangeActionPerformed(evt);
            }
        });

        Modern.setText("Confirmation");

        btnHitung.setText("Checkout");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radiochange)
                    .addComponent(radioyes)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Modern))
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(Modern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioyes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiochange, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 380, 140, 200);

        listPilih.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPilih);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 240, 90, 140);

        btnCopy.setText(">>");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });
        getContentPane().add(btnCopy);
        btnCopy.setBounds(120, 280, 50, 29);

        listToping.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Honney", "Butter", "Cardamom", "Syrup", "Vanila", "Milk" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listToping.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTopingValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listToping);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(27, 240, 90, 140);

        combopayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gopay", "Dana", "Ovo" }));
        getContentPane().add(combopayment);
        combopayment.setBounds(280, 240, 95, 27);

        txtResume.setColumns(2);
        txtResume.setRows(1);
        txtResume.setTabSize(1);
        jScrollPane3.setViewportView(txtResume);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(190, 420, 200, 160);

        background.setIcon(new javax.swing.ImageIcon("/Users/apple/Desktop/bg.png")); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 410, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chckcapuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckcapuccinoActionPerformed
        // TODO add your handling code here:
        if (chckcapuccino.isSelected()){
            txtcapuccino.setEditable(true);
            txtcapuccino.setText("1");
        }else {
            txtcapuccino.setEditable(false);
            txtcapuccino.setText("0");
        }
    }//GEN-LAST:event_chckcapuccinoActionPerformed

    private void chckexpressooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckexpressooActionPerformed
        if (chckexpressoo.isSelected()){
            txtexpresso.setEditable(true);
            txtexpresso.setText("1");
            
        }else {
            txtexpresso.setEditable(false);
            txtexpresso.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_chckexpressooActionPerformed

    private void chckamericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckamericanoActionPerformed
        if (chckamericano.isSelected()){
            txtamericano.setEditable(true);
            txtamericano.setText("1");
        }else {
            txtexpresso.setEditable(false);
            txtexpresso.setText("0");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_chckamericanoActionPerformed

    private void txtexpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexpressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexpressoActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int nExpressoo = Integer.parseInt(txtexpresso.getText());
        int nAmericano = Integer.parseInt(txtamericano.getText());
        int nCapuccino = Integer.parseInt(txtcapuccino.getText());
        
        //Total harganya
        int nTotal = (8000 * nExpressoo)+(10000 * nAmericano)+(4000 * nCapuccino);

        if (radioyes.isSelected()){
            
            // Variable instance
            String menu1 = "   Expresso  : "+txtexpresso.getText();
            String menu2 = "   Americano : "+txtamericano.getText();
            String menu3 = "   Capucinno : "+txtcapuccino.getText();
            String metodebayar = combopayment.getSelectedItem().toString();
            String toping = listPilih.getModel().toString();
            
            //Nampilkan di resume
            String sResume = "-Minuman-\n"+menu1+"\n"+menu2+"\n"+menu3+"\n"+"\nMetode :"+metodebayar+"\nToping :"+toping+"\n"+"\n"+"Total : "+ "Rp."+nTotal;
            txtResume.setText(sResume);
        } else if(radiochange.isSelected()){
            chckexpressoo.setSelected(false);
            chckamericano.setSelected(false);
            chckcapuccino.setSelected(false);
            combopayment.setSelectedItem(false);
            
            //RemoveToping
            listPilih.removeAll();
            txtResume.setText("");
        }
        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void radioyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioyesActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
        // TODO add your handling code here:
        pilih.addElement(listToping.getSelectedValue());
        //setelah ditambah, hitung jumlah pilihan
        int size = pilih.getSize();
    }//GEN-LAST:event_btnCopyActionPerformed

    private void listTopingValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTopingValueChanged
        // TODO add your handling code here:
        int index =listToping.getSelectedIndex();
        String kuliah = listToping.getSelectedValue();
    }//GEN-LAST:event_listTopingValueChanged

    private void radiochangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiochangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiochangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Modern;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnHitung;
    private javax.swing.JCheckBox chckamericano;
    private javax.swing.JCheckBox chckcapuccino;
    private javax.swing.JCheckBox chckexpressoo;
    private javax.swing.JComboBox<String> combopayment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listPilih;
    private javax.swing.JList<String> listToping;
    private javax.swing.JRadioButton radiochange;
    private javax.swing.JRadioButton radioyes;
    private javax.swing.JTextArea txtResume;
    private javax.swing.JTextField txtamericano;
    private javax.swing.JTextField txtcapuccino;
    private javax.swing.JTextField txtexpresso;
    // End of variables declaration//GEN-END:variables
}
